export default {
    TREE_LABELS_VALUE_REQUEST:"TREE_LABELS_VALUE_REQUEST",
    TREE_LABELS_VALUE_SUCCESS:"TREE_LABELS_VALUE_SUCCESS",
    TREE_LABELS_VALUE_FAILURE:"TREE_LABELS_VALUE_FAILURE",
    TREE_TYPES_REQUEST: "TREE_TYPES_REQUEST",
    TREE_TYPES_SUCCESS: "TREE_TYPES_SUCCESS",
    TREE_TYPES_FAILURE: "TREE_TYPES_FAILURE",
}